config/routes.rb
Rails.application.routes.draw do 

	root 'welcome#index'


	post 'links' => 'links#index'


 
  

	resources :links
 	devise_for :users
  

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord

	belongs_to :user

	has_many :comments

	has_many :votes

	validates :post, presence: true


	#def links
	#	if link.include?("http://") || link.include?("https://")
	#end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         serialize :following, Array

         has_many :links

         has_many :comments

         validates :username, presence: true, uniqueness: true



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


	before_filter :authenticate_user!  

	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

	  def configure_permitted_parameters

	    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :location])

	    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :location])

		end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user! 

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:post, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@links = []

  	Link.all.each do |link|
  		if current_user || current_user.id == link.user
  			@links.push(link)
  		end
  	end
  end

  def show_user
  	@user = User.find(params[:id].to_i)
  	current_user.save

  	redirect_to show_user(id: params[:id])
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Treddit</title>
    <%= csrf_meta_tags %>

    <nav class="navbar navbar-default" id="nav">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Home</a>
    </div>
      
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search Links">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
  </div>
</nav>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>












  	<div class="col-md-3 col-md-offset-9">
  <% if user_signed_in? %>
  	<p><%= link_to "Edit Profile", edit_user_registration_path %></p>
  	<p><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></p>
  	<% end %>
  </div>
  	<div class="container">
    <%= yield %>
    
  </div>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for(link) do |f| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post %>
    <%= f.text_field :post %>
  </div>

  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-success" %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>
    
    <h1><strong>Links</strong></h1>

    <div class="row">
      <div class="col-md-8 col-md-offset-1">
        <% @links.each do |link| %>
              <%= link_to link.user.name, show_link_path(id: link.user_id) %><span class="blue-text"><%= link_to"@#{link.user.username}" %> &#8227; <%= time_ago_in_words(link.created_at) %></span>
            </div>
          </div>
          
              <div class="row">
                <div class="col-md-8">
                  <%= link_to 'Edit', edit_link_path(link) %> | <%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </div>
    </div>

<br>

<%= link_to new_link_path do %>
<span class= "glyphicon glyphicon-plus"></span> New Link
<% end %>

app/views/links/new.html.erb
<div class="row">
	<div class="well">
<h1>Post Something New</h1>



<%= render 'form', link: @link %>
</div>
</div>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @link.post %>
</p>

<p>
  <strong>User:</strong>
  <%= @link.user_id %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/welcome/about.html.erb
<div class="row">
		<div class="col-md=4 col-md-offset-4">
		<h1> Welcome to Reddit</h1> 
	</div>
</div>

app/views/welcome/index.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-2">
        <h1>Welcome to Party Links <%= current_user.username %></h1>
        <p> Where <strong>LINKS</strong> gets <strong>JUDGED</strong></p>
    </div>
  </div>
  
<br>

<div>
	<% @links.each do |link| %>
	<div>
		<p>@<%= link.user.username %></p>
		<p>@<%= link.post.html_safe %></p>
	</div>
	<% end %>
</div>

<br>








<%= link_to new_link_path do %>
<span class= "glyphicon glyphicon-plus"></span> New Link
<% end %>